services:
  - type: web
    name: kisansathi-api
    runtime: go
    plan: free

    buildCommand: go build -o bin/kisansathi-api ./app/main.go
    startCommand: ./bin/kisansathi-api

    healthCheckPath: /health

    envVars:
      - key: DATABASE_PASSWORD
        sync: false